[project]
name = "reconoscope-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dnspython[async]>=2.8.0",
    "httpx[http2]>=0.28.1",
    "phonenumbers>=9.0.15",
]
